### ISSUE TITLE
Request the code of sparse matrix version

### ISSUE THREAD

**Issue by dg4271** [Ian09/CF-NADE#4]
Hello, 
I really interest of your model 'CF-NADE'. 
However, when i test using my own dataset with h5py(like MovieLens1M), i get a memory error.
Could please release the code about sparse matrix version of code? 
I think you maybe use sciply sparse matrix when experimenting with Netflix of MovieLens 10M data.

I need your help, thanks

**Comment by Ian09** [comment]
Please tell me your email address. ;-)

**Comment by dg4271** [comment]
dg4271@naver.com
if it is okay can i receive the implicit feedback version (recsys16) as well?
Thank you!  :-)
