### ISSUE TITLE
How to calculate MAE

### ISSUE THREAD

**Issue by doremiks7** [Ian09/CF-NADE#7]
Hi sir, please give me equation to calculate MAE in Testing. i need it so much. Please tell me as soon as possible. Thanks a lot

**Comment by Ian09** [comment]
https://en.wikipedia.org/wiki/Mean_absolute_error this one, i think.

**Comment by doremiks7** [comment]
Thank you a lot for replying. But in your NADE code. i have tried to calculate MAE in below code. But it seem not correct when i run on google colab.

se = np.sum(np.square(true_r - pred_r) * mask)

            tong = np.sum(abs(true_r - pred_r))

            n = np.sum(mask)
            squared_error_valid.append(se)
            n_sample_valid.append(n)

        squared_error_ = np.array(squared_error_valid).sum()
        n_samples = np.array(n_sample_valid).sum()


        valid_MAE = tong/n

        valid_RMSE = np.sqrt(squared_error_ / (n_samples * 1.0 + 1e-8))
        print ('Validation:', " RMSE: {0:.6f}".format(valid_RMSE) , "Valid Time: {0:.6f}".format(valid_time), get_done_text(start_time),)
        print ('Validation:', " MAE: {0:.6f}".format(valid_MAE))

**Comment by Ian09** [comment]
I use RMSE, not MAE

**Comment by doremiks7** [comment]
Yes, sir. MAE is that the part I added. You could give me code to calculate MAE. I will be extremely
grateful you. Thank you

**Comment by Ian09** [comment]
I think It is not complicated, you are able to do it ;-)

**Comment by doremiks7** [comment]
oh no. actually. i don't understand what your code. it's too different normal models.

**Comment by Ian09** [comment]
is it difficult? se = np.sum(np.square(true_r - pred_r) * mask) clearly specifies how to compute squared error.

**Comment by doremiks7** [comment]
oh thank you.
because se have a part that is mask. it's make me confused. Thank you sir a lot.

**Comment by Ian09** [comment]
you can just ignore/remove mask. I  did not clear out the demo code.

**Comment by doremiks7** [comment]
thank you sir. by the way. If ordering o is permutation by timestamp DESC with specify user . it better than when ordering o is random ?. thank you sir

**Comment by Ian09** [comment]
You can try it. But I don't think it would be better, since you do not have the groundtruth timestamp.

**Comment by doremiks7** [comment]
actually. i'm a student,  i only approach ML a little. But your code is too complex with me :smile: . i'm trying to test when ordering o by timestamp and without timestamp. i can preprocessing data with timestamp DESC for specify user, but i didn't chang permutation with timestamp. Anyway thank you so much for supporting me.

**Comment by doremiks7** [comment]
Hi sir. i have a quetstion. In your paper. you said: , we will omit the index u of ru and focus on a single user specific CF-NADE in the rest of the paper. So in the rest of the paper you presented next rates based on items rated. if chain of items rated is 5 star so next rates is 5 star too. Right? . Thank you sir

**Comment by Ian09** [comment]
I am sorry, I don't get what is your question

**Comment by doremiks7** [comment]
your question is that if a person only rated films with 5 star, so your model will predict next films with 5 star , Is it right?. thank you sir

**Comment by Ian09** [comment]
No, it is not right
